# Introducere în NumPy - Vectori și Matrici

Până acum am lucrat cu tipuri de date și colecții standard din Python, precum listele. Acum, vom face un pas înainte și vom explora una dintre cele mai puternice biblioteci pentru calcul numeric din Python: **NumPy** (Numerical Python).

**NumPy** este fundamentală pentru oricine lucrează în domeniul științei datelor (Data Science) sau inteligenței artificiale (AI), deoarece oferă o structură de date foarte eficientă, numită **ndarray** (n-dimensional array), care ne permite să efectuăm operații matematice complexe pe volume mari de date cu o viteză mult mai mare decât listele standard.

## De ce folosim NumPy?
	•	**Viteză**: Operațiile în NumPy sunt implementate în limbaje de nivel scăzut (cum ar fi C), ceea ce le face extrem de rapide.
	•	**Eficiență**: Array-urile NumPy ocupă mai puțin spațiu în memorie decât listele Python.
	•	**Funcționalități matematice**: Oferă o gamă largă de funcții matematice pentru a lucra cu vectori și matrici.

Pentru a putea folosi biblioteca, trebuie mai întâi să o importăm. Convenția standard este să o importăm sub aliasul `np`.

In [ ]:
# Exemplu 1: Importarea bibliotecii NumPy
import numpy as np

## Vectori (Array-uri 1D)

Cel mai simplu tip de array NumPy este **vectorul**, care este un array unidimensional (1D). Ne putem gândi la el ca la o listă de numere, dar folosită pentru calcule matematice.

In [ ]:
# Exemplu 2: Crearea unui vector dintr-o listă Python
lista_mea = [1, 5, 8, 12]
vector = np.array(lista_mea)

print("Vectorul nostru este:", vector)
print("Tipul de date al vectorului este:", type(vector))

# OBS.: Pentru a crea un array NumPy, folosim funcția `np.array()` și îi dăm ca
# parametru o listă. Observăm că tipul de date returnat este `numpy.ndarray`.

In [ ]:
# __EXERCIȚIU__ Creează o listă goală. Adaugă trei numere în interiorul său.
# Creează un vector NumPy pornind de la acea listă. Afișează vectorul pe ecran.

### Crearea Vectorilor cu Funcții NumPy

NumPy ne oferă și funcții specializate pentru a crea vectori rapid, fără a mai scrie manual o listă.

In [ ]:
# Exemplu 3: Crearea unui vector cu `np.arange()`
vector_range = np.arange(0, 10) # Generează numere de la 0 (inclusiv) la 10 (exclusiv)
print("Vector creat cu arange:", vector_range)

# OBS.: `np.arange()` funcționează foarte similar cu funcția `range()` din
# Python, dar returnează direct un array NumPy.

In [ ]:
# __EXERCIȚIU__
# Creează un vector care conține toate numerele pare de la 2 la 20 (inclusiv).
# Numește variabila `vector_par`.

# HINT: `np.arange()` acceptă trei parametri: `start`, `stop` și `pas`.

In [ ]:
# Exemplu 4: Crearea unui vector de zerouri sau de unu
vector_zerouri = np.zeros(5) # Creează un vector cu 5 elemente, toate egale cu 0
print("Vector de zerouri:", vector_zerouri)

vector_unu = np.ones(4) # Creează un vector cu 4 elemente, toate egale cu 1
print("Vector de unu:", vector_unu)

# OBS.: Aceste funcții sunt foarte utile pentru a inițializa array-uri.
# Implicit, tipul de date al elementelor este `float` (număr zecimal).

In [ ]:
# __EXERCIȚIU__
# Creează un vector cu 10 elemente, toate având valoarea 1.

## Matrici (Array-uri 2D)

O **matrice** este un array bidimensional (2D), organizat pe rânduri și coloane. Este echivalentul unei liste de liste, dar, din nou, mult mai eficientă.

In [ ]:
# Exemplu 5: Crearea unei matrici dintr-o listă de liste
lista_de_liste = [[1, 2, 3], [4, 5, 6]]
matrice = np.array(lista_de_liste)

print("Matricea noastră este:\n", matrice)

# OBS.: Fiecare listă interioară devine un rând al matricii. Este important ca
# toate listele interioare să aibă aceeași lungime.

In [ ]:
# __EXERCIȚIU__
# Creează o matrice de 3x3 (3 rânduri și 3 coloane) care să conțină numerele
# de la 1 la 9.
# Numește variabila `matrice_3x3`.

In [ ]:
# Exemplu 6: Crearea unei matrici cu `arange` și `reshape`

matrice_reshape = np.arange(1, 7).reshape(2, 3) # Creează un vector 1-6 și îl
                                                # remodelează într-o matrice de 2x3
print("Matrice creată cu reshape:\n", matrice_reshape)

# OBS.: Metoda `.reshape(randuri, coloane)` ne permite să remodelăm un vector
# într-o matrice. Numărul total de elemente (randuri * coloane) trebuie să
# corespundă cu numărul de elemente din vectorul inițial (în acest caz, 2*3 = 6).

In [ ]:
# __EXERCIȚIU__
# Creează o matrice de 4x5 care să conțină numerele de la 0 la 19.
# Folosește `np.arange()` și `.reshape()`.
# HINT: Asigură-te că numărul de elemente din `arange` este egal cu 4 * 5.

## Atributele Array-urilor

Fiecare array NumPy are atribute care ne oferă informații despre structura sa, cum ar fi dimensiunea și forma.

In [ ]:
# Exemplu 7: Verificarea atributelor unui array

matrice = np.arange(10).reshape(2, 5)
print("Matricea:\n", matrice)

print("Forma (shape):", matrice.shape) # Returnează un tuplu (rânduri, coloane)
print("Număr de dimensiuni (ndim):", matrice.ndim) # Returnează numărul de dimensiuni (2 pentru matrice)
print("Număr total de elemente (size):", matrice.size) # Returnează numărul total de elemente

# OBS.:
# `.shape` este unul dintre cele mai utile atribute, spunându-ne exact cum sunt organizate datele.
# `.ndim` ne spune dacă avem un vector (1), o matrice (2) sau un tensor (3+).
# `.size` este pur și simplu numărul total de valori din array.

Matricea:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Forma (shape): (2, 5)
Număr de dimensiuni (ndim): 2
Număr total de elemente (size): 10


In [ ]:
# __EXERCIȚIU__
# Creează un vector cu 15 elemente de 0.
# Afișează forma și numărul de dimensiuni pentru acest vector.
# Remodelează vectorul într-o matrice de 3x5.
# Afișează forma și numărul de dimensiuni pentru noua matrice.

In [ ]:
# __EXERCIȚIU__ [!] Se dă un vector cu x elemente. Scrieți o funcție care ia
# ca parametru un vector, calculează lungimea sa, determină toate modurile
# în care acel vector poate fi remodelat ca și matrice și afișează toate acele
# remodelări.

# Ex.: x = 20 -> [1, 20], [2, 10], [4, 5], [5, 4], [10, 2], [20, 1]

## Indexare și Slicing

Similar cu listele Python, putem accesa elemente sau grupuri de elemente dintr-un array NumPy folosind **indexarea** și **slicing-ul**. Sintaxa este însă puțin diferită și mai puternică pentru matrici.

In [ ]:
# Exemplu 8: Indexarea unui element dintr-o matrice
matrice = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Matricea:\n", matrice)

# Accesăm elementul de pe rândul 1, coloana 2 (valoarea 60)
element = matrice[1, 2]
print("\nElementul de la [1, 2] este:", element)

# OBS.: Folosim sintaxa `[rand, coloana]`. Amintiți-vă că indexarea începe de la 0!

In [ ]:
# __EXERCIȚIU__
# Se dă matricea de mai jos.

matrice_test = np.arange(1, 13).reshape(3, 4)
print(matrice_test)

# Accesează și afișează numărul 5. Remodelează matricea cu forma (2, 6) și
# afișează din nou numărul 5.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Exemplu 9: Slicing - extragerea de rânduri și coloane
matrice = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Matricea:\n", matrice)

# Extragem primul rând complet
primul_rand = matrice[0, :] # sau mai simplu: matrice[0]
print("\nPrimul rând:", primul_rand)

# Extragem a doua coloană completă
a_doua_coloana = matrice[:, 1]
print("A doua coloană:", a_doua_coloana)

# OBS.: Simbolul `:` înseamnă "selectează tot" pe acea axă (rând sau coloană).

Matricea:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Primul rând: [10 20 30]
[10 20 30]
A doua coloană: [20 50 80]


In [ ]:
# __EXERCIȚIU__
# Folosind `matrice` de la exercițiul anterior:
# 1. Extrage și afișează ultimul rând.
# 2. Extrage și afișează a doua coloană.

In [ ]:
# Exemplu 10: Slicing - extragerea unei sub-matrici
matrice = np.arange(1, 33).reshape(4, 8)
print("Matricea originală:\n", matrice)

# Extragem o sub-matrice de 2x2 din colțul din stânga sus
# Rândurile 0 și 1, coloanele 0 și 1
sub_matrice = matrice[0:2, 0:2]
print("\nSub-matricea 2x2:\n", sub_matrice)

# OBS.: Sintaxa `start:stop` funcționează la fel ca la liste: `start` este inclus, `stop` este exclus.

Matricea originală:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]

Sub-matricea 2x2:
 [[ 1  2]
 [ 9 10]]


In [ ]:
# Exemplu 11: Slicing cu pas
sub_matrice = matrice[0:3,0:6:2]
print(sub_matrice)

# OBS.: Procesul de slicing se folosește semnificativ de logica range( ).

[[ 1  3  5]
 [ 9 11 13]
 [17 19 21]]


In [ ]:
# __EXERCIȚIU__
matrice = np.arange(1, 26).reshape(5, 5)
# Din matricea dată, extrage sub-matricea formată din ultimele două rânduri și
# ultimele două coloane.

## Exerciții Recapitulative

In [ ]:
# __EXERCIȚIU__ Tabla de șah simplificată
# 1. Creează o matrice de 8x8 umplută complet cu zerouri. Folosește `np.zeros()`.
# 2. Folosind slicing cu pas, modifică elementele pentru a semăna cu o tablă de șah (alternând 0 și 1).
#    - Setează toate elementele de pe poziții pare (rând par, coloană pară) la 1.
#    - Setează toate elementele de pe poziții impare (rând impar, coloană impară) la 1.
# 3. Afișează matricea finală.




# HINT: Pentru pas, sintaxa este `start:stop:pas`. Pentru a selecta toate
# rândurile/coloanele, poți scoate acel parametru din selecție (ex. [3::,::1]).

In [ ]:
# __EXERCIȚIU__
# Simulează aruncarea a două zaruri de 10 ori.
# 1. Creează o matrice de 10x2 unde fiecare element este un număr întreg aleator
# între 1 și 6 (inclusiv 6!).
# 2. Calculează suma rezultatelor pentru fiecare aruncare (suma pe rânduri).
# 3. Afișează matricea aruncărilor și vectorul sumelor.

# Operații Fundamentale și Manipularea Array-urilor

În capitolul anterior am învățat cum să creăm vectori și matrici folosind NumPy. Acum vom explora cum să manipulăm aceste array-uri și să efectuăm operații matematice de bază.

Aceste operații sunt esențiale în analiza datelor și inteligența artificială, deoarece ne permit să filtrăm, să transformăm și să agregăm datele într-un mod eficient. Vom învăța despre **selecția condiționată**, **operații element-cu-element** și **generarea de numere aleatoare**.

In [ ]:
# Nu uitați să importăm biblioteca NumPy
import numpy as np

## Selecția Condiționată

Selecția condiționată ne permite să extragem elemente dintr-un array care îndeplinesc o anumită condiție. Este una dintre cele mai puternice tehnici din NumPy.

In [ ]:
# Exemplu 1: Selecția cu măști booleene
vector = np.arange(10)
print("Vector original:", vector)

# Creăm o "mască" booleană
masca = vector > 5
print("Masca booleană (vector > 5):", masca)

# Aplicăm masca pentru a selecta elementele
print("Elementele mai mari decât 5:", vector[masca])

# OBS.: Când aplicăm o condiție unui array (ex: `vector > 5`), NumPy returnează
# un nou array de aceeași dimensiune, dar care conține valori `True` sau `False`.
# Acest array se numește **mască booleană**. Când folosim masca pentru indexare,
# sunt returnate doar elementele din array-ul original unde masca are valoarea `True`.

In [ ]:
# __EXERCIȚIU__
# Se dă matricea de mai jos.
matrice_note = np.array([[5, 8, 10], [4, 7, 3]])

# Selectează și afișează doar notele de trecere (>= 5).

In [ ]:
# Exemplu 2: Funcția np.where()
vector = np.arange(10)
print("Vector original:", vector)

# Înlocuim elementele mai mari ca 5 cu valoarea -1, iar pe celelalte le lăsăm neschimbate
vector_modificat = np.where(vector > 5, -1, vector)
print("Vector modificat:", vector_modificat)

# OBS.: Funcția `np.where()` funcționează ca o instrucțiune if-else pentru
# array-uri. Sintaxa este: `np.where(condiție, valoare_dacă_True, valoare_dacă_False)`.


# Putem folosi această regulă pentru a modifica și elemenetele cu True, și cele
# cu False.

matrice = np.array([[10, 20], [1, 2], [3, 4]])
matrice_mod = np.where(matrice > 5, 1, 0)

print(matrice_mod)

Vector original: [0 1 2 3 4 5 6 7 8 9]
Vector modificat: [ 0  1  2  3  4  5 -1 -1 -1 -1]
[[1 1]
 [0 0]
 [0 0]]


In [ ]:
# __EXERCIȚIU__
# Creează o matrice 3x3 cu numere de la 1 la 9.
# Folosind `np.where()`, înlocuiește toate numerele impare cu 0, iar pe cele
# pare lasă-le neschimbate.

## Funcții Agregate

Funcțiile agregate sunt funcții care realizează o operație pe un set de valori și returnează o singură valoare (ex: suma, media, minimul, maximul).

In [ ]:
# Exemplu 5: Suma elementelor cu .sum()
matrice = np.array([[1, 2, 3], [4, 5, 6]])
print("Matricea:\n", matrice)

# Suma tuturor elementelor
suma_totala = matrice.sum()
print("\nSuma totală:", suma_totala)

# Suma pe coloane (se colapsează rândurile)
suma_coloane = matrice.sum(axis=0)
print("Suma pe coloane:", suma_coloane)

# Suma pe rânduri (se colapsează coloanele)
suma_randuri = matrice.sum(axis=1)
print("Suma pe rânduri:", suma_randuri)

# OBS.: Parametrul `axis` este foarte important.
# `axis=0` înseamnă că operația se execută "în jos", pe coloane.
# `axis=1` înseamnă că operația se execută "în lateral", pe rânduri.

In [ ]:
# __EXERCIȚIU__
# O companie are vânzări în 4 trimestre pentru 3 regiuni diferite.
vanzari = np.array([[100, 120, 150, 130],  # Regiunea Nord
                     [80, 90, 100, 110],   # Regiunea Sud
                     [200, 210, 220, 230]]) # Regiunea Est

# 1. Calculează totalul vânzărilor pe fiecare trimestru (suma pe coloane).
# 2. Calculează totalul vânzărilor pentru fiecare regiune (suma pe rânduri).
# HINT: Folosește `.sum()` cu parametrul `axis` corespunzător.

## Alte Funcții Utile de Manipulare

Să vedem și alte câteva funcții NumPy esențiale.

In [ ]:
# Exemplu 6: Elemente unice cu np.unique()
vector_cu_duplicate = np.array([1, 2, 2, 3, 3, 3, 4, 1, 5])
unice = np.unique(vector_cu_duplicate)
print("Elementele unice:", unice)

# OBS.: `np.unique()` returnează un array sortat care conține doar elementele
# unice din array-ul original.

In [ ]:
# Exemplu 7: Adăugarea de elemente cu np.append()
vector = np.array([1, 2, 3])
vector_nou = np.append(vector, [4, 5])

print("Vectorul original:", vector)
print("Vectorul nou:", vector_nou)

# IMPORTANT: Spre deosebire de metoda `.append()` a listelor, `np.append()` NU
# modifică array-ul original. Ea returnează un array NOU care conține elementele
# vechi plus cele noi.

In [ ]:
# Exemplu 8: Matricea identitate cu np.eye()
matrice_identitate = np.eye(4)
print("Matricea identitate 4x4:\n", matrice_identitate)

# OBS.: O **matrice identitate** este o matrice pătratică
# (nr. rânduri = nr. coloane) care are 1 pe diagonala principală și 0 în rest.
# Este foarte importantă în algebra liniară.

In [ ]:
# __EXERCIȚIU__
# 1. Creează un vector cu numerele 10, 20, 30.
# 2. Adaugă la acest vector numerele 40, 20, 50, 60, 20, 70 și stochează
# rezultatul într-o variabilă nouă.
# 3. Transformă variabila nouă într-o matrice de 3x3.
# 4. Găsește elementele unice din noul array și afișează-le.
# 5. Creează o matrice identitate de 3x3 și adun-o la matricea inițială.
# 6. Afișează rezultatul.

## Generarea de Numere Aleatoare

Modulul `np.random` din NumPy este extrem de util pentru a genera date aleatoare, necesare pentru testare, simulări sau inițializarea algoritmilor de machine learning.

In [ ]:
# Exemplu 9: Generarea de întregi aleatori cu np.random.randint()

# Generează un vector de 5 numere întregi între 1 (inclusiv) și 100 (exclusiv)
intregi_aleatori = np.random.randint(1, 100, size=5)
print("Vector de întregi aleatori:", intregi_aleatori)

# Generează o matrice de 3x4 cu numere întregi între 0 și 10
matrice_aleatoare = np.random.randint(0, 10, size=(3, 4))
print("\nMatrice de întregi aleatori:\n", matrice_aleatoare)

# OBS.: Parametrul `size` determină forma array-ului rezultat. Poate fi un număr
# (pentru vector) sau un tuplu (pentru matrice).

In [ ]:
# Exemplu 10: Generarea de numere zecimale aleatoare

# Generează un număr aleator între 0 și 1
numar_random = np.random.random()
print(f"Un număr aleator între 0 și 1: {numar_random:.2f}")

# Generează un vector de 3 numere uniform distribuite între 10 și 20
vector_uniform = np.random.uniform(10, 20, size=3)
print("Vector uniform distribuit:", vector_uniform)

# Generează un vector de 5 numere dintr-o distribuție normală (Gaussiană)
vector_normal = np.random.normal(loc=0, scale=1, size=5)
print("Vector cu distribuție normală:", vector_normal)

# OBS.:
# `np.random.random()`: Generează numere între 0 și 1.

# `np.random.uniform(min, max)`: Generează numere unde fiecare valoare din
# interval are o șansă egală de a fi aleasă.

# `np.random.normal(loc, scale)`: Generează numere care se grupează în jurul
# unei valori medii (`loc`), cu o anumită împrăștiere (`scale`).

In [ ]:
# __EXERCIȚIU__ Înlocuirea chenarului
# 1. Creează o matrice de 5x5 umplută cu 1, folosind `np.ones()`.
# 2. Folosind slicing, selectează sub-matricea interioară (cea de 3x3, fără chenar).
# 3. Modifică valoarea acestei sub-matrici la 0.
# 4. Afișează matricea finală. Ar trebui să arate ca un chenar de 1 în jurul unei zone de 0.