# Operații Fundamentale cu Vectori și Matrici

Bun venit la un nou capitol! Până acum am lucrat cu date individuale, însă în Inteligența Artificială, datele sunt adesea grupate în structuri mai complexe, precum **vectorii** și **matricile**. Acestea ne permit să efectuăm operații matematice pe seturi mari de date într-un mod foarte eficient.

Pentru a lucra cu vectori și matrici în Python, vom folosi una dintre cele mai puternice biblioteci pentru calcul numeric: **NumPy**. O vom importa, de regulă, sub aliasul `np` pentru a scrie cod mai concis.

In [2]:
# Importarea bibliotecii NumPy
import numpy as np

## Operații de bază cu Vectori și Matrici

Operațiile fundamentale, precum adunarea, scăderea sau înmulțirea, se aplică diferit atunci când lucrăm cu vectori și matrici. Să explorăm cele mai comune operații.

### Adunarea și Scăderea

Adunarea și scăderea a doi vectori sau a două matrici se realizează **element cu element** (*element-wise*). Acest lucru înseamnă că fiecare element de pe o anumită poziție dintr-o matrice se adună (sau se scade) cu elementul de pe aceeași poziție din a doua matrice. Din acest motiv, operațiile necesită ca matricile să aibă **aceeași dimensiune** (același număr de rânduri și coloane).

In [ ]:
# Exemplu 1: Adunarea și scăderea a două matrici
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

suma = A + B
diferenta = A - B

print(f"Matricea A:\n{A}\n")
print(f"Matricea B:\n{B}\n")
print(f"Suma A + B:\n{suma}\n")
print(f"Diferența A - B:\n{diferenta}")

# OBS.: Operatorii `+` și `-` sunt supraîncărcați (overloaded) de NumPy pentru a
# funcționa element cu element. Dacă dimensiunile matricilor nu se potrivesc,
# NumPy va returna o eroare de tip `ValueError`.

In [7]:
# __EXERCIȚIU__ Se dau doi vectori, `v1` și `v2`.
# Calculați și afișați suma și diferența lor.

v1 = np.array([10, 20, 30])
v2 = np.array([5, 10, 15])

print(v1 + v2)
print(v1 - v2)

[15 30 45]
[ 5 10 15]


### Înmulțirea cu un scalar

Înmulțirea unei matrici cu un **scalar** (un singur număr) este o operație simplă: fiecare element al matricii este înmulțit cu acel număr. Această operație este utilă pentru a scala valorile dintr-un set de date.

In [ ]:
# Exemplu 2: Înmulțirea unei matrici cu un scalar
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
scalar = 10

rezultat = A * scalar

print(f"Matricea A:\n{A}\n")
print(f"Rezultatul A * {scalar}:\n{rezultat}")

In [8]:
# __EXERCIȚIU__ Avem o listă de prețuri în RON stocată într-un vector NumPy.
# Doriți să convertiți prețurile în Euro, considerând un curs de 5 RON/EUR.
# Înmulțiți vectorul cu scalarul corespunzător pentru a obține prețurile în Euro.

preturi_ron = np.array([50, 120, 75, 200])

print(preturi_ron * 0.2)
print(preturi_ron / 5)

# HINT: Puteți încerca și prin operația de împărțire.

[10. 24. 15. 40.]
[10. 24. 15. 40.]


In [12]:
# __EXERCIȚIU__
# Se dau prețurile unor produse fără TVA.
preturi_fara_tva = np.array([100, 250, 80, 120])
TVA = 0.19 # 19%

# Calculează prețurile cu TVA inclus (pret_fara_tva * 1.19) și stochează-le în
# variabila `preturi_cu_tva`. Afișează array-ul final.

preturi_cu_tva = preturi_fara_tva * 1.19
print(preturi_cu_tva)

masca = preturi_cu_tva > 120
print(masca)

preturi_mai_mari_decat_120 = preturi_cu_tva[masca]
print(preturi_mai_mari_decat_120)

# Selectează apoi doar acele prețuri care au valoarea peste 120 și adaugă-le
# într-un array nou.

[119.  297.5  95.2 142.8]
[False  True False  True]
[297.5 142.8]


### Produsul a două matrici (Matrix Multiplication)

Aceasta este una dintre cele mai importante operații. Spre deosebire de adunare, produsul a două matrici **NU** se face element cu element. Produsul matricial are o regulă specifică:

! Pentru a putea înmulți două matrici, `A` și `B`, numărul de coloane din prima matrice (`A`) trebuie să fie egal cu numărul de rânduri din a doua matrice (`B`).

Dacă `A` este o matrice `m x n` și `B` este `n x p`, atunci rezultatul `C = A @ B` va fi o matrice `m x p`.

In [3]:
# Exemplu 3: Produsul a două matrici
A = np.array([
    [1, 2, 3], # 2x3
    [4, 5, 6]
])

B = np.array([
    [7, 8],   # 3x2
    [9, 10],
    [11, 12]
])

# Folosim operatorul `@` pentru produsul matricial
C = A @ B

print(f"Matricea A (2x3):\n{A}\n")
print(f"Matricea B (3x2):\n{B}\n")
print(f"Produsul A @ B (2x2):\n{C}")

# OBS.: Produsul matricial nu este comutativ, adică `A @ B` este, în general,
# diferit de `B @ A`.
# De asemenea, operatorul `*` în NumPy realizează înmulțire element cu element
# și ar da eroare în acest caz din cauza dimensiunilor diferite.

Matricea A (2x3):
[[1 2 3]
 [4 5 6]]

Matricea B (3x2):
[[ 7  8]
 [ 9 10]
 [11 12]]

Produsul A @ B (2x2):
[[ 58  64]
 [139 154]]


In [ ]:
# __EXERCIȚIU__ Se dau două matrici 2x2, `M1` și `M2`.
# Calculați produsul `M1 @ M2` și afișați rezultatul.

M1 = np.array([[2, 0], [1, 3]])
M2 = np.array([[1, 1], [0, 2]])

# HINT: Folosiți `np.matmul(M1, M2)` sau, mai simplu, `M1 @ M2`.

### Transpusa unei matrici

Transpunerea unei matrici este operația prin care rândurile devin coloane și coloanele devin rânduri. Dacă avem o matrice `A` de dimensiune `m x n`, transpusa ei, notată $A^T$, va avea dimensiunea `n x m`.

In [4]:
# Exemplu 4: Transpusa unei matrici

A = np.array([
    [1, 2, 3], # 2x3
    [4, 5, 6]
])

# Folosim atributul .T pentru a obține transpusa
A_transpus = A.T

print(f"Matricea originală A (2x3):\n{A}\n")
print(f"Matricea transpusă A.T (3x2):\n{A_transpus}")

Matricea originală A (2x3):
[[1 2 3]
 [4 5 6]]

Matricea transpusă A.T (3x2):
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# __EXERCIȚIU__ Creați o matrice `M` de dimensiune 3x2.
# Găsiți și afișați transpusa acesteia.

M = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

# HINT: Atributul `.T` se adaugă direct la numele variabilei: `nume_matrice.T`.

## Determinantul și Inversa unei Matrici

Acestea sunt două proprietăți foarte importante ale **matricilor pătratice** (care au un număr egal de rânduri și coloane). Ele sunt piatra de temelie pentru rezolvarea sistemelor de ecuații liniare.

### Determinantul

Determinantul este un număr special (un scalar) care poate fi calculat dintr-o matrice pătratică. Valoarea sa ne oferă informații importante despre matrice. Cea mai importantă regulă de reținut este:

! O matrice al cărei determinant este **zero** se numește **singulară** și nu are o inversă.

In [ ]:
# Exemplu 5: Calculul determinantului

A = np.array([
    [3, 8],
    [4, 6]
])

det_A = np.linalg.det(A)

print(f"Matricea A:\n{A}\n")
print(f"Determinantul matricii A este: {det_A:.2f}") # (3*6) - (8*4) = 18 - 32 = -14

In [ ]:
# __EXERCIȚIU__ Se dă matricea `M`.
# Calculați și afișați determinantul său.

M = np.array([
    [1, 2],
    [3, 4]
])

# HINT: Folosiți funcția `np.linalg.det()`.

### Inversa unei matrici

Inversa unei matrici pătratice `A`, notată $A^{-1}$, este acea matrice specială care, atunci când este înmulțită cu `A`, produce **matricea identitate** `I` (o matrice cu `1` pe diagonala principală și `0` în rest).

$$ A \cdot A^{-1} = I $$

Doar matricile **non-singulare** (cu determinantul diferit de zero) au o inversă.

In [5]:
# Exemplu 6: Calculul inversei

# Matrice non-singulară
A = np.array([
    [1, 2],
    [3, 4]
])

A_inv = np.linalg.inv(A)
identitate = A @ A_inv

print(f"Matricea A:\n{A}\n")
print(f"Inversa A_inv:\n{A_inv}\n")
print(f"Produsul A @ A_inv (matricea identitate):\n{np.round(identitate)}")

# OBS.: Încercarea de a inversa o matrice singulară va produce o eroare `LinAlgError`.
B_singulara = np.array([
    [1, 2],
    [2, 4]
]) # det = 1*4 - 2*2 = 0
# np.linalg.inv(B_singulara) # Această linie ar opri execuția cu o eroare

Matricea A:
[[1 2]
 [3 4]]

Inversa A_inv:
[[-2.   1. ]
 [ 1.5 -0.5]]

Produsul A @ A_inv (matricea identitate):
[[1. 0.]
 [0. 1.]]


In [ ]:
# __EXERCIȚIU__ Găsiți inversa matricii `M` de mai jos și verificați
# că produsul dintre `M` și inversa sa este matricea identitate.

M = np.array([
    [2, 5],
    [1, 3]
])

# HINT: Folosiți `np.linalg.inv()` pentru a calcula inversa, apoi operatorul `@` pentru a le înmulți.

## Sisteme de Ecuații Liniare

O aplicație directă și foarte puternică a operațiilor cu matrici este rezolvarea sistemelor de ecuații liniare. Aceste sisteme apar frecvent în aproape toate domeniile științifice și tehnice.

### Reprezentarea sub formă de matrici

Un sistem de ecuații, precum cel de mai jos:
$$ \begin{cases} x_{1} + x_{2} = 4 \\ 2x_{1} - x_{2} = 5 \end{cases} $$

poate fi rescris sub forma compactă $A \cdot x = y$, unde:

* `A` este **matricea coeficienților** (numerele din fața variabilelor).
* `x` este **vectorul variabilelor** (necunoscutele pe care vrem să le aflăm).
* `y` este **vectorul constantelor** (rezultatele ecuațiilor).

$$ A = \begin{bmatrix} 1 & 1 \\ 2 & -1 \end{bmatrix}, \quad x = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}, \quad y = \begin{bmatrix} 4 \\ 5 \end{bmatrix} $$

### Rezolvarea cu ajutorul inversei

Dacă avem ecuația $A \cdot x = y$, putem afla vectorul `x` prin înmulțirea la stânga cu inversa $A^{-1}$:

$$ A^{-1} \cdot (A \cdot x) = A^{-1} \cdot y $$
$$ (A^{-1} \cdot A) \cdot x = A^{-1} \cdot y $$
$$ I \cdot x = A^{-1} \cdot y $$
$$ x = A^{-1} \cdot y $$

Prin urmare, soluția sistemului este produsul dintre inversa matricii coeficienților și vectorul constantelor.

In [6]:
# Exemplu 7: Rezolvarea unui sistem de ecuații

# Sistemul: x1 + x2 = 4  |  2*x1 - x2 = 5

# Matricea coeficienților
A = np.array([
    [1, 1],
    [2, -1]
])

# Vectorul constantelor
y = np.array([4, 5])

# Calculăm soluția folosind inversa
A_inv = np.linalg.inv(A)
x = A_inv @ y

print(f"Soluția sistemului (x1, x2) este: {x}") # Rezultatul este x1=3, x2=1

# OBS.: O metodă mai directă și mai stabilă numeric în NumPy este folosirea
# funcției `np.linalg.solve(A, y)`. Aceasta rezolvă sistemul fără a calcula
# explicit inversa, fiind adesea mai rapidă și mai precisă.

x_solve = np.linalg.solve(A, y)
print(f"Soluția folosind np.linalg.solve: {x_solve}")

Soluția sistemului (x1, x2) este: [3. 1.]
Soluția folosind np.linalg.solve: [3. 1.]


In [ ]:
# __EXERCIȚIU__ O excursie pe munte costă 30 RON per copil și 32 RON per adult,
# cu un total încasat de 1184 RON.
# La întoarcere, transportul a costat 35 RON per copil și 36 RON per adult,
# totalul fiind de 1352 RON.

# Sistemul de ecuații este:
# 30*c + 32*a = 1184
# 35*c + 36*a = 1352

# Folosiți NumPy pentru a afla câți copii (c) și câți adulți (a) au fost în excursie.



# HINT: Definiți matricea A a coeficienților (numerele din fața lui `c` și `a`)
# și vectorul y al constantelor (totalurile încasate).